### ISSUE TITLE
Allows decimals for Staking and Unstaking DAD

### ISSUE THREAD

**Issue by jbuck84** [tvl83/daddydao#14]
The fields to enter how much DAD you want to stake or unstake do not appear to support decimals.

**Comment by tvl83** [comment]
Thank you for reporting this! 

![image](https://user-images.githubusercontent.com/141966/94100268-cb1fe700-fdf2-11ea-92d9-a41c8354350f.png)

This will be what it looks like.

Let me know any more feedback. :)
