### ISSUE TITLE
"Suggestion" for Price, Volume, etc. inclusion on website

### ISSUE THREAD

**Issue by CryptDo** [tvl83/daddydao#23]
How about a USD/EOS Price / Volume / ???  feed? 

Could be a click box option or the like to see it or not see it. The website is beautifully arranged, concise, pleasing on the eyes (e.g. night mode look, layout of sections, shape, ease of use, etc. I don't want to make cluttering the simplicity of the view mandatory. But I'm not a developer so not sure of the work involved to put an on off clickbox or the like there; Just putting the idea out there. 

Background - Right now, I find myself looking at [https://bloks.io/tokens/DAD-eos-dadtoken1111](url) every day as watching the volume increase, price move all over the place, etc. - It all gives me an idea of the interest and growth of the project. 

Appreciated

**Comment by tvl83** [comment]
This is on the site already. I forgot to update this issue. 

Currently it only updates on page load. I can make it a live feed later.
